-- MySQL Script generated by MySQL Workbench
-- 12/08/17 19:56:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BaseProjectDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `BaseProjectDB` ;

-- -----------------------------------------------------
-- Schema BaseProjectDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BaseProjectDB` DEFAULT CHARACTER SET utf8 ;
USE `BaseProjectDB` ;

-- -----------------------------------------------------
-- Table `BaseProjectDB`.`usergroup`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseProjectDB`.`usergroup` ;

CREATE TABLE IF NOT EXISTS `BaseProjectDB`.`usergroup` (
  `idusergroup` INT NOT NULL AUTO_INCREMENT,
  `groupname` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idusergroup`),
  UNIQUE INDEX `idgroup_UNIQUE` (`idusergroup` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProjectDB`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseProjectDB`.`user` ;

CREATE TABLE IF NOT EXISTS `BaseProjectDB`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NULL,
  `group_idgroup` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `surname1` VARCHAR(255) NULL,
  `surname2` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `iduser_UNIQUE` (`iduser` ASC),
  INDEX `fk_user_group1_idx` (`group_idgroup` ASC),
  CONSTRAINT `fk_user_group1`
    FOREIGN KEY (`group_idgroup`)
    REFERENCES `BaseProjectDB`.`usergroup` (`idusergroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProjectDB`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseProjectDB`.`role` ;

CREATE TABLE IF NOT EXISTS `BaseProjectDB`.`role` (
  `idrole` VARCHAR(20) NOT NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`idrole`),
  UNIQUE INDEX `idrole_UNIQUE` (`idrole` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProjectDB`.`usergroup_has_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseProjectDB`.`usergroup_has_role` ;

CREATE TABLE IF NOT EXISTS `BaseProjectDB`.`usergroup_has_role` (
  `usergroup_idusergroup` INT NOT NULL,
  `role_idrole` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`usergroup_idusergroup`, `role_idrole`),
  INDEX `fk_usergroup_has_role_role1_idx` (`role_idrole` ASC),
  INDEX `fk_usergroup_has_role_usergroup1_idx` (`usergroup_idusergroup` ASC),
  CONSTRAINT `fk_usergroup_has_role_usergroup1`
    FOREIGN KEY (`usergroup_idusergroup`)
    REFERENCES `BaseProjectDB`.`usergroup` (`idusergroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usergroup_has_role_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `BaseProjectDB`.`role` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProjectDB`.`guestbook`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseProjectDB`.`guestbook` ;

CREATE TABLE IF NOT EXISTS `BaseProjectDB`.`guestbook` (
  `idguestbook` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `message` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idguestbook`),
  UNIQUE INDEX `idguestbook_UNIQUE` (`idguestbook` ASC),
  INDEX `fk_guestbook_user1_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_guestbook_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `BaseProjectDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProjectDB`.`picture`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseProjectDB`.`picture` ;

CREATE TABLE IF NOT EXISTS `BaseProjectDB`.`picture` (
  `idpicture` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `filekey` VARCHAR(32) NOT NULL,
  `filepath` VARCHAR(255) NULL,
  `filename` VARCHAR(255) NOT NULL,
  `fileextension` VARCHAR(45) NULL,
  `creationdate` DATETIME NULL,
  PRIMARY KEY (`idpicture`),
  INDEX `fk_pictues_user1_idx` (`user_iduser` ASC),
  UNIQUE INDEX `key_UNIQUE` (`filekey` ASC),
  CONSTRAINT `fk_pictues_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `BaseProjectDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BaseProjectDB`.`userpreferences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BaseProjectDB`.`userpreferences` ;

CREATE TABLE IF NOT EXISTS `BaseProjectDB`.`userpreferences` (
  `iduserpreferences` INT NOT NULL AUTO_INCREMENT,
  `user_iduser` INT NOT NULL,
  `repositorypath` VARCHAR(255) NOT NULL,
  `picture_idpicture` INT NOT NULL,
  `numresultsinpage` INT NOT NULL,
  INDEX `fk_userpreferences_user1_idx` (`user_iduser` ASC),
  UNIQUE INDEX `repositorypath_UNIQUE` (`repositorypath` ASC),
  INDEX `fk_userpreferences_picture1_idx` (`picture_idpicture` ASC),
  PRIMARY KEY (`iduserpreferences`),
  UNIQUE INDEX `iduserpreferences_UNIQUE` (`iduserpreferences` ASC),
  CONSTRAINT `fk_userpreferences_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `BaseProjectDB`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userpreferences_picture1`
    FOREIGN KEY (`picture_idpicture`)
    REFERENCES `BaseProjectDB`.`picture` (`idpicture`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
